Name:           ros-kinetic-rh-p12-rn-gui
Version:        0.1.0
Release:        0%{?dist}
Summary:        ROS rh_p12_rn_gui package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/rh_p12_rn_gui
Source0:        %{name}-%{version}.tar.gz

Requires:       qt-devel
Requires:       ros-kinetic-qt-build
Requires:       ros-kinetic-rh-p12-rn-base-module-msgs
Requires:       ros-kinetic-robotis-controller-msgs
Requires:       ros-kinetic-roscpp
BuildRequires:  qt-devel
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-qt-build
BuildRequires:  ros-kinetic-rh-p12-rn-base-module-msgs
BuildRequires:  ros-kinetic-robotis-controller-msgs
BuildRequires:  ros-kinetic-roscpp

%description
This package provides GUI interface to control the RH-P12-RN

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Mar 22 2018 Pyo <pyo@robotis.com> - 0.1.0-0
- Autogenerated by Bloom

